//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureStorageSyncClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IStorageService")]
    public interface IStorageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/CreateEmpty", ReplyAction="http://tempuri.org/IData/CreateEmptyResponse")]
        void CreateEmpty(string name, int len, bool random);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/CreateEmpty", ReplyAction="http://tempuri.org/IData/CreateEmptyResponse")]
        System.Threading.Tasks.Task CreateEmptyAsync(string name, int len, bool random);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/CreateAppend", ReplyAction="http://tempuri.org/IData/CreateAppendResponse")]
        void CreateAppend(string name, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/CreateAppend", ReplyAction="http://tempuri.org/IData/CreateAppendResponse")]
        System.Threading.Tasks.Task CreateAppendAsync(string name, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/CreateReplace", ReplyAction="http://tempuri.org/IData/CreateReplaceResponse")]
        void CreateReplace(string name, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/CreateReplace", ReplyAction="http://tempuri.org/IData/CreateReplaceResponse")]
        System.Threading.Tasks.Task CreateReplaceAsync(string name, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/Read", ReplyAction="http://tempuri.org/IData/ReadResponse")]
        byte[] Read(string name, int offset, int lenght);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/Read", ReplyAction="http://tempuri.org/IData/ReadResponse")]
        System.Threading.Tasks.Task<byte[]> ReadAsync(string name, int offset, int lenght);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/Copy", ReplyAction="http://tempuri.org/IData/CopyResponse")]
        void Copy(string src_name, string dst_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/Copy", ReplyAction="http://tempuri.org/IData/CopyResponse")]
        System.Threading.Tasks.Task CopyAsync(string src_name, string dst_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/Move", ReplyAction="http://tempuri.org/IData/MoveResponse")]
        void Move(string src_name, string dst_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/Move", ReplyAction="http://tempuri.org/IData/MoveResponse")]
        System.Threading.Tasks.Task MoveAsync(string src_name, string dst_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/Delete", ReplyAction="http://tempuri.org/IData/DeleteResponse")]
        void Delete(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/Delete", ReplyAction="http://tempuri.org/IData/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GetLength", ReplyAction="http://tempuri.org/IData/GetLengthResponse")]
        long GetLength(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GetLength", ReplyAction="http://tempuri.org/IData/GetLengthResponse")]
        System.Threading.Tasks.Task<long> GetLengthAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GetCount", ReplyAction="http://tempuri.org/IData/GetCountResponse")]
        int GetCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GetCount", ReplyAction="http://tempuri.org/IData/GetCountResponse")]
        System.Threading.Tasks.Task<int> GetCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/Exists", ReplyAction="http://tempuri.org/IData/ExistsResponse")]
        bool Exists(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/Exists", ReplyAction="http://tempuri.org/IData/ExistsResponse")]
        System.Threading.Tasks.Task<bool> ExistsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GetNames", ReplyAction="http://tempuri.org/IData/GetNamesResponse")]
        string[] GetNames(int idx, int len);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GetNames", ReplyAction="http://tempuri.org/IData/GetNamesResponse")]
        System.Threading.Tasks.Task<string[]> GetNamesAsync(int idx, int len);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GetAllNames", ReplyAction="http://tempuri.org/IData/GetAllNamesResponse")]
        string[] GetAllNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GetAllNames", ReplyAction="http://tempuri.org/IData/GetAllNamesResponse")]
        System.Threading.Tasks.Task<string[]> GetAllNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/DeleteAll", ReplyAction="http://tempuri.org/IData/DeleteAllResponse")]
        void DeleteAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/DeleteAll", ReplyAction="http://tempuri.org/IData/DeleteAllResponse")]
        System.Threading.Tasks.Task DeleteAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/SHA256", ReplyAction="http://tempuri.org/IData/SHA256Response")]
        byte[] SHA256(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/SHA256", ReplyAction="http://tempuri.org/IData/SHA256Response")]
        System.Threading.Tasks.Task<byte[]> SHA256Async(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStorageServiceChannel : SecureStorageSyncClient.ServiceReference.IStorageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorageServiceClient : System.ServiceModel.ClientBase<SecureStorageSyncClient.ServiceReference.IStorageService>, SecureStorageSyncClient.ServiceReference.IStorageService {
        
        public StorageServiceClient() {
        }
        
        public StorageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateEmpty(string name, int len, bool random) {
            base.Channel.CreateEmpty(name, len, random);
        }
        
        public System.Threading.Tasks.Task CreateEmptyAsync(string name, int len, bool random) {
            return base.Channel.CreateEmptyAsync(name, len, random);
        }
        
        public void CreateAppend(string name, byte[] data) {
            base.Channel.CreateAppend(name, data);
        }
        
        public System.Threading.Tasks.Task CreateAppendAsync(string name, byte[] data) {
            return base.Channel.CreateAppendAsync(name, data);
        }
        
        public void CreateReplace(string name, byte[] data) {
            base.Channel.CreateReplace(name, data);
        }
        
        public System.Threading.Tasks.Task CreateReplaceAsync(string name, byte[] data) {
            return base.Channel.CreateReplaceAsync(name, data);
        }
        
        public byte[] Read(string name, int offset, int lenght) {
            return base.Channel.Read(name, offset, lenght);
        }
        
        public System.Threading.Tasks.Task<byte[]> ReadAsync(string name, int offset, int lenght) {
            return base.Channel.ReadAsync(name, offset, lenght);
        }
        
        public void Copy(string src_name, string dst_name) {
            base.Channel.Copy(src_name, dst_name);
        }
        
        public System.Threading.Tasks.Task CopyAsync(string src_name, string dst_name) {
            return base.Channel.CopyAsync(src_name, dst_name);
        }
        
        public void Move(string src_name, string dst_name) {
            base.Channel.Move(src_name, dst_name);
        }
        
        public System.Threading.Tasks.Task MoveAsync(string src_name, string dst_name) {
            return base.Channel.MoveAsync(src_name, dst_name);
        }
        
        public void Delete(string name) {
            base.Channel.Delete(name);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string name) {
            return base.Channel.DeleteAsync(name);
        }
        
        public long GetLength(string name) {
            return base.Channel.GetLength(name);
        }
        
        public System.Threading.Tasks.Task<long> GetLengthAsync(string name) {
            return base.Channel.GetLengthAsync(name);
        }
        
        public int GetCount() {
            return base.Channel.GetCount();
        }
        
        public System.Threading.Tasks.Task<int> GetCountAsync() {
            return base.Channel.GetCountAsync();
        }
        
        public bool Exists(string name) {
            return base.Channel.Exists(name);
        }
        
        public System.Threading.Tasks.Task<bool> ExistsAsync(string name) {
            return base.Channel.ExistsAsync(name);
        }
        
        public string[] GetNames(int idx, int len) {
            return base.Channel.GetNames(idx, len);
        }
        
        public System.Threading.Tasks.Task<string[]> GetNamesAsync(int idx, int len) {
            return base.Channel.GetNamesAsync(idx, len);
        }
        
        public string[] GetAllNames() {
            return base.Channel.GetAllNames();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllNamesAsync() {
            return base.Channel.GetAllNamesAsync();
        }
        
        public void DeleteAll() {
            base.Channel.DeleteAll();
        }
        
        public System.Threading.Tasks.Task DeleteAllAsync() {
            return base.Channel.DeleteAllAsync();
        }
        
        public byte[] SHA256(string name) {
            return base.Channel.SHA256(name);
        }
        
        public System.Threading.Tasks.Task<byte[]> SHA256Async(string name) {
            return base.Channel.SHA256Async(name);
        }
    }
}
